name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Install Playwright Browsers
      run: |
        cd CRMTest
        dotnet build
        pwsh bin/Debug/net8.0/playwright.ps1 install

    - name: Run Tests
      run: dotnet test CRMTest --logger trx
