name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies and build
        run: |
          cd crm-site/client
          npm ci
          npm run build

      - name: Build backend
        run: |
          cd crm-site/server
          dotnet build

      - name: Start backend server
        run: |
          cd crm-site/server
          dotnet run &
          sleep 5

      - name: Install Playwright Browsers
        run: |
          cd CRMTest
          dotnet build
          pwsh bin/Debug/net9.0/playwright.ps1 install

      - name: Run Playwright tests
        run: |
          cd CRMTest
          dotnet test --logger trx

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [test] # Only runs if 'test' job passed
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd `/srv/www/malmo/hiba/` || git clone git@github.com:Hiba-Khaleel/CRM-Testing.git
            cd CRM-Testing
            git pull
